services:
  stroopwafel:
    image: ghcr.io/joeblack2k/stroopwafel-linkedin-cron:latest
    container_name: stroopwafel
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /absolute/path/to/your/stroopwafel-data:/data
